### ISSUE TITLE
The setting of --dataset

### ISSUE THREAD

**Issue by anlimo1510** [soo89/CSD-SSD#10]
Hi Jisoo, thanks for your nice work. 
could you tell me what --dataset is? Does it mean using the different configuration settings for different sizes of inputs? For example, VOC300 refers to the setting for an ssd300 model while VOC512 refers to ssd512?

**Comment by soo89** [comment]
You are right

I got the wrong name while making the code.

**Comment by anlimo1510** [comment]
Good to know. Thank you!
