### ISSUE TITLE
consistency_conf_loss

### ISSUE THREAD

**Issue by GUN-xing** [soo89/CSD-SSD#11]
in paper, the consistency_conf_loss is JSD. but in the code, the consistency_conf_loss is sum of 2 KL
![image](https://user-images.githubusercontent.com/34390030/106438644-b72b7680-64b1-11eb-99e9-e8f3c1cc85ab.png)
How do I understand this consistency_conf_loss_a and consistency_conf_loss_a.
JSD should be like this
![image](https://user-images.githubusercontent.com/34390030/106439604-d4147980-64b2-11eb-9be2-1872bec49d68.png)

thanks

**Comment by soo89** [comment]
Thanks for your interest in our research.

consistency_conf_loss_a => KLD( f(hat(I)) | f(I))
consistency_conf_loss_b => KLD( f(I) | f(hat(I))

please check the following link ( https://discuss.pytorch.org/t/kl-divergence-produces-negative-values/16791 )
Thank you

**Comment by soo89** [comment]
Thanks for your interest.
And you are right.
It is Jeffreys divergence. 
Thanks for pointing out the incorrect part.
Thank you.

**Comment by GUN-xing** [comment]
Thanks for your reply
I got it

**Comment by soo89** [comment]
Thank you for your interest.

And, Thank you for pointing out our mistake. 

First of all, you are right. 

I applied alpha-Jensen-Shannon divergence with (alpha = 1). 

Precisely, It is Jeffreys divergence.
