### ISSUE TITLE
if I want to train the CSD mode, whether I should not set the start_iter equal to zero

### ISSUE THREAD

**Issue by 18120226** [soo89/CSD-SSD#13]
if I want to train the CSD mode, whether I should not set the start_iter equal to zero

**Comment by soo89** [comment]
As far as I understand, you would like to train the CSD model the same as our paper.
In our case, we trained the CSD model with 'train_csd.py' from 'start_iter = 0'.

**Comment by 18120226** [comment]
But in the line 167 " if(args.start_iter==0)" , it will used the function "VOCDetection_con_init" which do not include the unlabel data

**Comment by soo89** [comment]
For the stable training, we train with only labeled data in the first epoch. 

Please check in 'voc07_consistency_init.py' (Line 98) and 'voc07_consistency.py'(Line 103) files.

**Comment by 18120226** [comment]
what this error "_jb_pytest_runner.py: error: unrecognized arguments: E:/software/pycharmProjects/CSD-SSD-master_v2/CSD-SSD-master/eval512.py" means

**Comment by soo89** [comment]
The file 'eval512.py' is for the SSD512 model.  

Have you trained with the SSD512 model?
