### ISSUE TITLE
The failure of download code

### ISSUE THREAD

**Issue by zwy1996** [soo89/CSD-SSD#6]
Hello, Thanks for your nice work!

When I downloaded your code, I tried many times but failed.
I thought maybe beacause of your "weight" folder that had the 70 M pretrained model.

Could you please delete the weight folder and offer another pretrained model link?

Thank you very much!

**Comment by soo89** [comment]
Would you download our next research code?
(https://github.com/soo89/ISD-SSD)

There are included CSD code and no weight file.

You can download a pre-trained weight file from the following link.
(https://github.com/amdegroot/ssd.pytorch)
