### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by namihagi** [soo89/CSD-SSD#8]
I'm interested in this paper.
So I'd like to train this model on custom datasets, but failed to train.
Could you tell me which version of pytorch and cuda you use?
thank you!

**Comment by soo89** [comment]
Thanks for your interest.

I trained CSD with the following environment.
Python 3.6
CUDA 10.0
Pytorch 1.0.0

**Comment by namihagi** [comment]
I trained correctly.
thank you so much!
